### ISSUE TITLE
2 Errors in Team mode

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#482]
1. 
![capture](https://cloud.githubusercontent.com/assets/19422415/22547438/2c17af08-e974-11e6-817b-86b7f810496b.PNG)

2. Can't spawn with **Update Branch** in Agar client, or this happen when i use Cigar client

![captures](https://cloud.githubusercontent.com/assets/19422415/22547632/10b84f46-e975-11e6-8fec-3f926ee3e379.PNG)

**Comment by Luka967** [comment]
Agar client is weird currently. Every time you reset the server you'll need to restart agar too.

**Comment by RasyiidWho** [comment]
@Luka967 Now i hate Moneyclip Agar.

**Comment by Gigabyte918** [comment]
so play other Agar.io like games XD

**Comment by Megabyte918** [comment]
@RasyiidWho It is an issue with the new protocol, I will fix this when I'm working on the leaderboard in FFA

**Comment by AlexHGaming** [comment]
@Megabyte918 Close now?

**Comment by AlexHGaming** [comment]
@Megabyte918 You might as well close as everything's fixed in the merged pull request.

**Comment by Megabyte918** [comment]
The teams leaderboard still needs rewriting.

**Comment by AlexHGaming** [comment]
@Megabyte918 Doesn't show that he's collaborator when he posts a comment.

**Comment by Agarian** [comment]
This is very old, these errors no longer happen, the leaderboard does work fine now, however teams is still broken, so RIP.

**Comment by Agarian** [comment]
You could try looking back to 1.5.1, the Teams leaderboard still works there (at least on mine it does).

**Comment by Agarian** [comment]
@RasyiidWho This issue has actually been fixed by https://github.com/Megabyte918/MultiOgar-Edited/pull/1268. Now just wait until it's merged, then download the latest version.

**Comment by Agarian** [comment]
@Fan7asy @Megabyte918 close?
